# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'AuthenticationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AuthenticationService
   pod 'Firebase/Auth'
   pod 'Firebase/Analytics'
   pod 'Firebase/Crashlytics'
   pod 'GoogleSignIn'

  target 'AuthenticationServiceTests' do
    # Pods for testing
  end

end
